version: "3.9"

services:
  redis:
    image: redis:7-alpine

  web:
    build: .
    command: gunicorn beaunity.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A myproject worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data:  # You can remove this if you remove db service
