# Generated by Django 5.2.2 on 2025-06-28 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(5)]
            ),
        ),
    ]
