# Generated by Django 5.2.2 on 2025-07-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_post", "Can approve posts"),
                    ("can_post_without_approval", "Can post without approval"),
                ],
            },
        ),
    ]
