# Generated by Django 5.2.2 on 2025-08-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_alter_comment_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_by",
            new_name="user",
        ),
    ]
