# Generated by Django 5.2.2 on 2025-06-08 12:35

import beaunity.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', beaunity.accounts.managers.AppUserManager()),
            ],
        ),
    ]
