# Generated by Django 5.2.2 on 2025-06-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
