# Generated by Django 5.2.2 on 2025-07-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_joined_events'),
        ('challenge', '0006_alter_challenge_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_challenges',
            field=models.ManyToManyField(related_name='challenge_attendees', to='challenge.challenge'),
        ),
    ]
