# Generated by Django 5.2.2 on 2025-07-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_joined_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_challenges',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joined_events',
        ),
    ]
