# Generated by Django 5.2.2 on 2025-06-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="online",
            new_name="is_online",
        ),
    ]
