# Generated by Django 5.2.2 on 2025-06-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
    ]
