# Generated by Django 5.2.2 on 2025-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0014_alter_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
