# Generated by Django 5.2.2 on 2025-07-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_event_is_new"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name_plural": "Events"},
        ),
    ]
