# Generated by Django 5.2.2 on 2025-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0016_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(),
        ),
    ]
