# Generated by Django 5.2.2 on 2025-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0002_alter_challenge_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
