# Generated by Django 5.2.2 on 2025-07-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='progress',
        ),
    ]
