# Generated by Django 5.2.2 on 2025-07-07 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_remove_challenge_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='participants',
        ),
        migrations.AddField(
            model_name='challenge',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='challenge_attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
