# Generated by Django 5.2.2 on 2025-07-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_remove_challenge_participants_challenge_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Legenary', 'Legenary')], default='Beginner', max_length=15),
        ),
    ]
