# Generated by Django 5.2.2 on 2025-07-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0007_challenge_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Legendary", "Legendary"),
                ],
                default="Beginner",
                max_length=15,
            ),
        ),
    ]
