# Generated by Django 5.2.2 on 2025-07-27 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0008_alter_challenge_difficulty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="challenge_attendees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
