# Generated by Django 5.2.3 on 2025-06-22 06:41

import django.core.validators
import organizer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=110, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s-]+$', 'The company name is invalid!', code='invalid_company_name')])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[organizer.validators.OnlyDigitsValidator()])),
                ('secret_key', models.CharField(max_length=4, validators=[organizer.validators.FourUniqueDigitsValidator()])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
