# Generated by Django 5.2.2 on 2025-06-21 09:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, default="", max_length=255, null=True
            ),
        ),
    ]
