# Generated by Django 5.2.2 on 2025-06-21 11:11

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
    ]
